set(CXX_SERVICE_TEMPLATE_COMPILER_FLAGS
    -Werror
    -Wall
    -Wextra
    -Wcast-align
    -Wcast-qual
    -Wconversion
    -Wextra-semi
    -Wsign-compare
    -Wsign-conversion
    -pedantic
    -pedantic-errors
)
